# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

# TODO Rust builds on stable by default, this can be
# overridden on a case by case basis down below.

env:
  global:
    - CRATE_NAME=suzanne-metadata

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: f+WLKMtdvUbHFT6bK49VIJXIxqlPCJ4+57aNK+SCllD5eD4v90tZgN1rj73WPLLtl6j8QsYQUQV0JXZQrXVh/dI3iAsyxZkvHdvj7iZig5ZF/cRfhGGUR2ybnC7qXKCjfChTyPnl7XMgCYwug0Tk0NNq23LC47TOHuwTJbT4GnJ/hDQvbON/OkwNHz314HW+DM6+5aQyN4jvmDML5GPO6M37aWKgfgvR+W0kKK8uAJliHvB7ma1erxuZve4cFUr1RWKy2KsMPoIoKzAxDVRNL/7EFnPjGCALgVQ8mICdd2bMkXRBtCDDqv5Bz0m++S5N8u+R3QeSZkV8yKIPlXV2iH99OhJnDP2f85yCvHPdFcoxEDGudyxzV0bNq2V2uuWhuRgdAfPOygS7Rtvk/9Ld0swr/REJDNvFi8fF0Foj3GtY75ckMTMDrwc75RmWsjyrleVob4c2ybe90HERbHhIydwjz492srs51yeJ+cVSD0yykNxQP/tBLxYahhkc5lfvfDl+Z90lgk6pYE+HNTvp8ZOzH1+WyUz1+7jiEk2w4SoAEuCx0t5KSgt4goLfLrZ+N5WDur4NpfLRru5c1QcDOFYR8F9GfRBwvCK3aLgiD65wpJi3E19bbvtrsWkOkZiVuPCJ3/qsHwQ6GsQdZpWWwesDEw1l3jDXrnu+jWVPaN4=
    file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
