[package]
name = "suzanne-metadata"
version = "0.1.0"
authors = ["Mukund Lakshman <yaymukund@gmail.com>"]
publish = false

[dependencies]
walkdir = "2.0.1"
id3 = "0.2.2"
indicatif = "0.8.0"
filetime = "0.1"
clap = "2"
